/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module player_display_12 (
    input clk,
    input rst,
    input [7:0] player_position,
    input screen,
    input [4:0] x,
    input [2:0] y,
    output reg [23:0] color
  );
  
  
  
  reg [2:0] player_y;
  
  reg [4:0] player_x;
  
  always @* begin
    color = 24'h000000;
    if (screen == 1'h0 && player_position[7+0-:1] == 1'h0) begin
      player_y = 3'h0 + player_position[5+1-:2] + 2'h2;
      player_x = player_position[0+4-:5];
    end else begin
      if (screen == 1'h1 && player_position[7+0-:1] == 1'h1) begin
        player_y = 3'h0 + player_position[5+1-:2] + 1'h1;
        player_x = 5'h1f - player_position[0+4-:5];
      end else begin
        player_y = 8'h00;
        player_x = 8'h00;
      end
    end
    if (player_x == x) begin
      if (player_y == y || player_y == y + 1'h1 || player_y == y + 2'h2) begin
        color = 24'h00ff00;
      end
    end
  end
endmodule
