/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module player_move_8 (
    input [7:0] b,
    input clk,
    input rst,
    output reg [7:0] res
  );
  
  
  
  reg [4:0] x;
  reg [2:0] y;
  
  reg [7:0] player_position;
  
  reg [7:0] player_move;
  
  reg [7:0] new_position;
  
  reg [7:0] M_player_position_dff_d, M_player_position_dff_q = 8'h61;
  
  always @* begin
    M_player_position_dff_d = M_player_position_dff_q;
    
    player_move = b;
    player_position = M_player_position_dff_q;
    new_position = M_player_position_dff_q;
    x = player_position[0+4-:5];
    y = player_position[5+2-:3];
    if (b == 1'h1) begin
      if (y[2+0-:1] == 1'h0) begin
        new_position[7+0-:1] = 1'h1;
      end else begin
        new_position[7+0-:1] = 1'h0;
      end
    end else begin
      new_position[7+0-:1] = M_player_position_dff_q[7+0-:1];
    end
    res = new_position;
    M_player_position_dff_d = new_position;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_player_position_dff_q <= 8'h61;
    end else begin
      M_player_position_dff_q <= M_player_position_dff_d;
    end
  end
  
endmodule
