/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_ish_2 (
    input [7:0] state,
    output reg [119:0] out
  );
  
  
  
  always @* begin
    
    case (state)
      8'h00: begin
        out = 120'h606062636465666768696a6b6c6d6e;
      end
      8'h01: begin
        out = 120'h606062636465666768696a6b6c6d60;
      end
      8'h02: begin
        out = 120'h606062636465666768696a6b6c606e;
      end
      8'h03: begin
        out = 120'h606062636465666768696a6b606d6e;
      end
      8'h04: begin
        out = 120'h606062636465666768696a606c6dee;
      end
      8'h05: begin
        out = 120'h60616263646566676869606b6cedee;
      end
      8'h06: begin
        out = 120'h606162636465666768606a6beced6e;
      end
      8'h07: begin
        out = 120'h606162636465666760696aebec6d60;
      end
      8'h08: begin
        out = 120'h60616263646566606869eaeb6c60ee;
      end
      8'h09: begin
        out = 120'h606162636465606768e9ea6b60ed60;
      end
      8'h0a: begin
        out = 120'h6061626364606667e8e96a60ec60ee;
      end
      8'h0b: begin
        out = 120'h60616263606566e7e86960eb60ed6e;
      end
      8'h0c: begin
        out = 120'h606162606465e6e76860ea60ec6d60;
      end
      8'h0d: begin
        out = 120'h6061606364e5e66760e960eb6c6060;
      end
      8'h0e: begin
        out = 120'h60606263e4e56660e860ea6b606060;
      end
      8'h0f: begin
        out = 120'h606162e3e46560e760e96a60606060;
      end
      8'h10: begin
        out = 120'h6061e2e36460e660e8696060606060;
      end
      8'h11: begin
        out = 120'h60e1e26360e560e768606060606060;
      end
      8'h12: begin
        out = 120'he0e16260e460e667606060606060ee;
      end
      8'h13: begin
        out = 120'he06160e360e566606060606060ed60;
      end
      8'h14: begin
        out = 120'h6060e260e465606060606060ec60ee;
      end
      8'h15: begin
        out = 120'h60e160e364606060606060eb60ed6e;
      end
      8'h16: begin
        out = 120'he060e263606060606060ea60ec6d6e;
      end
      8'h17: begin
        out = 120'h60e162606060606060e960eb6c6d6e;
      end
      8'h18: begin
        out = 120'he061606060606060e860ea6b6c6d6e;
      end
      8'h19: begin
        out = 120'h60606060606060e760e96a6b6c6d6e;
      end
      8'h1a: begin
        out = 120'h606060606060e660e8696a6b6c6d60;
      end
      8'h1b: begin
        out = 120'h6060606060e560e768696a6b6c60ee;
      end
      8'h1c: begin
        out = 120'h60606060e460e66768696a6b60ed60;
      end
      8'h1d: begin
        out = 120'h606060e360e5666768696a60ec6060;
      end
      8'h1e: begin
        out = 120'h6060e260e4656667686960eb6060ee;
      end
      8'h1f: begin
        out = 120'h60e160e3646566676860ea6060ed60;
      end
      8'h20: begin
        out = 120'he060e2636465666760e96060ec606e;
      end
      8'h21: begin
        out = 120'h60e1626364656660e86060eb606d60;
      end
      8'h22: begin
        out = 120'he0616263646560e76060ea606c6060;
      end
      8'h23: begin
        out = 120'h606162636460e66060e9606b6060ee;
      end
      8'h24: begin
        out = 120'h6061626360e56060e8606a6060edee;
      end
      8'h25: begin
        out = 120'h60616260e46060e760696060eced60;
      end
      8'h26: begin
        out = 120'h606160e36060e660686060ebec606e;
      end
      8'h27: begin
        out = 120'h6060e26060e560676060eaeb606d60;
      end
      8'h28: begin
        out = 120'h60e16060e460666060e9ea606c6060;
      end
      8'h29: begin
        out = 120'he06060e360656060e8e9606b606060;
      end
      8'h2a: begin
        out = 120'h6060e260646060e7e8606a6060606e;
      end
      8'h2b: begin
        out = 120'h60e160636060e6e760696060606dee;
      end
      8'h2c: begin
        out = 120'he060626060e5e660686060606ced60;
      end
      8'h2d: begin
        out = 120'h60616060e4e560676060606bec60ee;
      end
      8'h2e: begin
        out = 120'h606060e3e460666060606aeb60ed60;
      end
      8'h2f: begin
        out = 120'h6060e2e3606560606069ea60ec606e;
      end
      8'h30: begin
        out = 120'h60e1e2606460606068e960eb606dee;
      end
      8'h31: begin
        out = 120'he0e1606360606067e860ea606ced60;
      end
      8'h32: begin
        out = 120'he0606260606066e760e9606bec60ee;
      end
      8'h33: begin
        out = 120'h606160606065e660e8606aeb60ed60;
      end
      8'h34: begin
        out = 120'h6060606064e560e76069ea60ec6060;
      end
      8'h35: begin
        out = 120'h60606063e460e66068e960eb60606e;
      end
      8'h36: begin
        out = 120'h606062e360e56067e860ea60606dee;
      end
      8'h37: begin
        out = 120'h6061e260e46066e760e960606cedee;
      end
      8'h38: begin
        out = 120'h60e160e36065e660e860606becedee;
      end
      8'h39: begin
        out = 120'he060e26064e560e760606aebecedee;
      end
      8'h3a: begin
        out = 120'h60e16063e460e6606069eaebeced6e;
      end
      8'h3b: begin
        out = 120'he06062e360e5606068e9eaebec6dee;
      end
      8'h3c: begin
        out = 120'h6061e260e4606067e8e9eaeb6cedee;
      end
      8'h3d: begin
        out = 120'h60e160e3606066e7e8e9ea6beced60;
      end
      8'h3e: begin
        out = 120'he060e2606065e6e7e8e96aebec606e;
      end
      8'h3f: begin
        out = 120'h60e1606064e5e6e7e869eaeb606dee;
      end
      8'h40: begin
        out = 120'he0606063e4e5e6e768e9ea606ced6e;
      end
      8'h41: begin
        out = 120'h606062e3e4e5e667e8e9606bec6d60;
      end
      8'h42: begin
        out = 120'h6061e2e3e4e566e7e8606aeb6c6060;
      end
      8'h43: begin
        out = 120'h60e1e2e3e465e6e76069ea6b60606e;
      end
      8'h44: begin
        out = 120'he0e1e2e364e5e66068e96a60606d60;
      end
      8'h45: begin
        out = 120'he0e1e263e4e56067e86960606c606e;
      end
      8'h46: begin
        out = 120'he0e162e3e46066e76860606b606dee;
      end
      8'h47: begin
        out = 120'he061e2e36065e66760606a606ced60;
      end
      8'h48: begin
        out = 120'h60e1e26064e566606069606bec6060;
      end
      8'h49: begin
        out = 120'he0e16063e465606068606aeb606060;
      end
      8'h4a: begin
        out = 120'he06062e3646060676069ea6060606e;
      end
      8'h4b: begin
        out = 120'h6061e2636060666068e96060606d60;
      end
      8'h4c: begin
        out = 120'h60e1626060656067e86060606c6060;
      end
      8'h4d: begin
        out = 120'he0616060646066e76060606b606060;
      end
      8'h4e: begin
        out = 120'h606060636065e66060606a60606060;
      end
      8'h4f: begin
        out = 120'h6060626064e56060606960606060ee;
      end
      8'h50: begin
        out = 120'h60616063e46060606860606060edee;
      end
      8'h51: begin
        out = 120'h606062e36060606760606060eced60;
      end
      8'h52: begin
        out = 120'h6061e26060606660606060ebec6060;
      end
      8'h53: begin
        out = 120'h60e16060606560606060eaeb606060;
      end
      8'h54: begin
        out = 120'he06060606460606060e9ea60606060;
      end
      8'h55: begin
        out = 120'h6060606360606060e8e96060606060;
      end
      8'h56: begin
        out = 120'h60606260606060e7e8606060606060;
      end
      8'h57: begin
        out = 120'h606160606060e6e760606060606060;
      end
      8'h58: begin
        out = 120'h6060606060e5e660606060606060ee;
      end
      8'h59: begin
        out = 120'h60606060e4e560606060606060edee;
      end
      8'h5a: begin
        out = 120'h606060e3e460606060606060eced60;
      end
      8'h5b: begin
        out = 120'h6060e2e360606060606060ebec6060;
      end
      8'h5c: begin
        out = 120'h60e1e260606060606060eaeb60606e;
      end
      8'h5d: begin
        out = 120'he0e160606060606060e9ea60606dee;
      end
      8'h5e: begin
        out = 120'he060606060606060e8e960606ced60;
      end
      8'h5f: begin
        out = 120'h60606060606060e7e860606bec6060;
      end
      8'h60: begin
        out = 120'h606060606060e6e760606aeb60606e;
      end
      8'h61: begin
        out = 120'h6060606060e5e6606069ea60606d6e;
      end
      8'h62: begin
        out = 120'h60606060e4e5606068e960606c6dee;
      end
      8'h63: begin
        out = 120'h606060e3e4606067e860606b6ced60;
      end
      default: begin
        out = 120'h000000000000000000000000000000;
      end
    endcase
  end
endmodule
