/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module screen_display_1 (
    input clk,
    input rst,
    input [7:0] player_position,
    input [151:0] branch_positions,
    output reg led
  );
  
  
  
  wire [5-1:0] M_led_matrix_x;
  wire [3-1:0] M_led_matrix_y;
  wire [9-1:0] M_led_matrix_pixel;
  wire [1-1:0] M_led_matrix_screen;
  wire [1-1:0] M_led_matrix_led;
  reg [1-1:0] M_led_matrix_update;
  reg [24-1:0] M_led_matrix_color;
  dual_matrix_11 led_matrix (
    .clk(clk),
    .rst(rst),
    .update(M_led_matrix_update),
    .color(M_led_matrix_color),
    .x(M_led_matrix_x),
    .y(M_led_matrix_y),
    .pixel(M_led_matrix_pixel),
    .screen(M_led_matrix_screen),
    .led(M_led_matrix_led)
  );
  
  wire [24-1:0] M_player_color_color;
  reg [1-1:0] M_player_color_screen;
  reg [5-1:0] M_player_color_x;
  reg [3-1:0] M_player_color_y;
  player_display_12 player_color (
    .clk(clk),
    .rst(rst),
    .player_position(player_position),
    .screen(M_player_color_screen),
    .x(M_player_color_x),
    .y(M_player_color_y),
    .color(M_player_color_color)
  );
  wire [24-1:0] M_branch_color_color;
  reg [5-1:0] M_branch_color_x;
  reg [3-1:0] M_branch_color_y;
  reg [1-1:0] M_branch_color_screen;
  branch_display_13 branch_color (
    .clk(clk),
    .rst(rst),
    .branch_positions(branch_positions),
    .x(M_branch_color_x),
    .y(M_branch_color_y),
    .screen(M_branch_color_screen),
    .color(M_branch_color_color)
  );
  
  always @* begin
    M_led_matrix_update = 1'h1;
    led = M_led_matrix_led;
    M_player_color_screen = M_led_matrix_screen;
    M_player_color_x = M_led_matrix_x;
    M_player_color_y = M_led_matrix_y;
    M_branch_color_screen = M_led_matrix_screen;
    M_branch_color_x = M_led_matrix_x;
    M_branch_color_y = M_led_matrix_y;
    M_led_matrix_color = 24'h000000;
    if (M_branch_color_color == 24'h00893c) begin
      M_led_matrix_color = M_branch_color_color;
    end else begin
      M_led_matrix_color = (M_player_color_color);
    end
    if ((M_led_matrix_screen == 1'h0 && (M_led_matrix_y == 2'h2 || M_led_matrix_y == 1'h1) && M_led_matrix_x != 1'h0) || (M_led_matrix_screen == 1'h1 && (M_led_matrix_y == 3'h5 || M_led_matrix_y == 3'h6))) begin
      M_led_matrix_color = 24'h00873a;
    end
    if ((M_led_matrix_screen == 1'h0 && (M_led_matrix_x == 1'h0 || M_led_matrix_x == 5'h1f) || (M_led_matrix_screen == 1'h1 && (M_led_matrix_x == 5'h1f | M_led_matrix_x == 1'h0)))) begin
      M_led_matrix_color = 24'h010101;
    end
    if ((M_led_matrix_screen == 1'h0 && ((M_led_matrix_x == 5'h1f && M_led_matrix_y == 2'h3) | (M_led_matrix_x == 5'h1e && M_led_matrix_y == 3'h6) | (M_led_matrix_x == 5'h1b && M_led_matrix_y == 3'h5) | (M_led_matrix_x == 5'h17 && M_led_matrix_y == 2'h3) | (M_led_matrix_x == 5'h16 && M_led_matrix_y == 2'h2) | (M_led_matrix_x == 5'h19 && M_led_matrix_y == 2'h3))) | (M_led_matrix_screen == 1'h1 && ((M_led_matrix_x == 1'h0 && M_led_matrix_y == 2'h2)) | (M_led_matrix_x == 2'h2 && M_led_matrix_y == 2'h2) | (M_led_matrix_x == 3'h4 && M_led_matrix_y == 3'h4) | (M_led_matrix_x == 3'h7 && M_led_matrix_y == 2'h3 | (M_led_matrix_x == 4'ha && M_led_matrix_y == 1'h1) | (M_led_matrix_x == 4'h9 && M_led_matrix_y == 2'h3)))) begin
      M_led_matrix_color = 24'h000077;
    end
  end
endmodule
