/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg outled,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [7:0] state;
  
  wire [1-1:0] M_display_led;
  reg [8-1:0] M_display_player_position;
  reg [80-1:0] M_display_enemy_positions;
  hanoi_display_1 display (
    .clk(clk),
    .rst(rst),
    .player_position(M_display_player_position),
    .enemy_positions(M_display_enemy_positions),
    .led(M_display_led)
  );
  
  wire [80-1:0] M_rom_out_state;
  rom_ish_2 rom (
    .state(state),
    .out_state(M_rom_out_state)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_3 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    io_led = io_dip;
    io_seg = 8'hff;
    io_sel = 4'hf;
    led = io_dip[0+0+7-:8];
    state = io_dip[16+7-:8];
    M_display_player_position = io_dip[0+0+7-:8];
    M_display_enemy_positions = M_rom_out_state;
    outled = M_display_led;
  end
endmodule
