/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_ish_2 (
    input [7:0] state,
    output reg [151:0] out
  );
  
  
  
  always @* begin
    
    case (state)
      8'h00: begin
        out = 152'h60606060606060606060606060606060606060;
      end
      8'h01: begin
        out = 152'h60606060606060606060606060606060606060;
      end
      8'h02: begin
        out = 152'h60606060606060606060606060606060606060;
      end
      8'h03: begin
        out = 152'h60606060606060606060606060606060606060;
      end
      8'h04: begin
        out = 152'h6060606060606060606060606060606060f160;
      end
      8'h05: begin
        out = 152'h60606060606060606060606060606060f06060;
      end
      8'h06: begin
        out = 152'h606060606060606060606060606060ef606072;
      end
      8'h07: begin
        out = 152'h6060606060606060606060606060ee60607172;
      end
      8'h08: begin
        out = 152'h60606060606060606060606060ed6060707160;
      end
      8'h09: begin
        out = 152'h606060606060606060606060ec60606f7060f2;
      end
      8'h0a: begin
        out = 152'h6060606060606060606060eb60606e6f60f172;
      end
      8'h0b: begin
        out = 152'h60606060606060606060ea60606d6e60f07160;
      end
      8'h0c: begin
        out = 152'h606060606060606060e960606c6d60ef706060;
      end
      8'h0d: begin
        out = 152'h6060606060606060e860606b6c60ee6f6060f2;
      end
      8'h0e: begin
        out = 152'h60606060606060e760606a6b60ed6e6060f1f2;
      end
      8'h0f: begin
        out = 152'h606060606060e66060696a60ec6d6060f0f172;
      end
      8'h10: begin
        out = 152'h6060606060e56060686960eb6c6060eff07160;
      end
      8'h11: begin
        out = 152'h60606060e46060676860ea6b6060eeef706060;
      end
      8'h12: begin
        out = 152'h606060e36060666760e96a6060edee6f606060;
      end
      8'h13: begin
        out = 152'h6060e26060656660e8696060eced6e60606072;
      end
      8'h14: begin
        out = 152'h60e16060646560e7686060ebec6d60606071f2;
      end
      8'h15: begin
        out = 152'he06060636460e6676060eaeb6c60606070f160;
      end
      8'h16: begin
        out = 152'h6060626360e5666060e9ea6b6060606ff06072;
      end
      8'h17: begin
        out = 152'h60616260e4656060e8e96a6060606eef607160;
      end
      8'h18: begin
        out = 152'h606160e3646060e7e8696060606dee60706060;
      end
      8'h19: begin
        out = 152'h6060e2636060e6e7686060606ced606f606072;
      end
      8'h1a: begin
        out = 152'h60e1626060e5e6676060606bec606e60607160;
      end
      8'h1b: begin
        out = 152'he0616060e4e5666060606aeb606d6060706060;
      end
      8'h1c: begin
        out = 152'h606060e3e46560606069ea606c60606f606072;
      end
      8'h1d: begin
        out = 152'h6060e2e36460606068e9606b60606e60607160;
      end
      8'h1e: begin
        out = 152'h60e1e26360606067e8606a60606d6060706060;
      end
      8'h1f: begin
        out = 152'he0e16260606066e7606960606c60606f6060f2;
      end
      8'h20: begin
        out = 152'he06160606065e6606860606b60606e6060f1f2;
      end
      8'h21: begin
        out = 152'h6060606064e5606760606a60606d6060f0f160;
      end
      8'h22: begin
        out = 152'h60606063e4606660606960606c6060eff060f2;
      end
      8'h23: begin
        out = 152'h606062e3606560606860606b6060eeef60f160;
      end
      8'h24: begin
        out = 152'h6061e2606460606760606a6060edee60f06060;
      end
      8'h25: begin
        out = 152'h60e160636060666060696060eced60ef606060;
      end
      8'h26: begin
        out = 152'he060626060656060686060ebec60ee60606060;
      end
      8'h27: begin
        out = 152'h60616060646060676060eaeb60ed6060606060;
      end
      8'h28: begin
        out = 152'h606060636060666060e9ea60ec6060606060f2;
      end
      8'h29: begin
        out = 152'h6060626060656060e8e960eb6060606060f160;
      end
      8'h2a: begin
        out = 152'h60616060646060e7e860ea6060606060f06060;
      end
      8'h2b: begin
        out = 152'h606060636060e6e760e96060606060ef606060;
      end
      8'h2c: begin
        out = 152'h6060626060e5e660e86060606060ee60606060;
      end
      8'h2d: begin
        out = 152'h60616060e4e560e76060606060ed6060606060;
      end
      8'h2e: begin
        out = 152'h606060e3e460e66060606060ec606060606060;
      end
      8'h2f: begin
        out = 152'h6060e2e360e56060606060eb60606060606060;
      end
      8'h30: begin
        out = 152'h60e1e260e46060606060ea60606060606060f2;
      end
      8'h31: begin
        out = 152'he0e160e36060606060e960606060606060f160;
      end
      8'h32: begin
        out = 152'he060e26060606060e860606060606060f06060;
      end
      8'h33: begin
        out = 152'h60e16060606060e760606060606060ef6060f2;
      end
      8'h34: begin
        out = 152'he06060606060e660606060606060ee6060f160;
      end
      8'h35: begin
        out = 152'h6060606060e560606060606060ed6060f060f2;
      end
      8'h36: begin
        out = 152'h60606060e460606060606060ec6060ef60f160;
      end
      8'h37: begin
        out = 152'h606060e360606060606060eb6060ee60f06060;
      end
      8'h38: begin
        out = 152'h6060e260606060606060ea6060ed60ef606072;
      end
      8'h39: begin
        out = 152'h60e160606060606060e96060ec60ee60607172;
      end
      8'h3a: begin
        out = 152'he060606060606060e86060eb60ed6060707160;
      end
      8'h3b: begin
        out = 152'h60606060606060e76060ea60ec60606f706060;
      end
      8'h3c: begin
        out = 152'h606060606060e66060e960eb60606e6f606060;
      end
      8'h3d: begin
        out = 152'h6060606060e56060e860ea60606d6e60606060;
      end
      8'h3e: begin
        out = 152'h60606060e46060e760e960606c6d60606060f2;
      end
      8'h3f: begin
        out = 152'h606060e36060e660e860606b6c60606060f160;
      end
      8'h40: begin
        out = 152'h6060e26060e560e760606a6b60606060f06060;
      end
      8'h41: begin
        out = 152'h60e16060e460e66060696a60606060ef606060;
      end
      8'h42: begin
        out = 152'he06060e360e56060686960606060ee606060f2;
      end
      8'h43: begin
        out = 152'h6060e260e46060676860606060ed606060f160;
      end
      8'h44: begin
        out = 152'h60e160e36060666760606060ec606060f060f2;
      end
      8'h45: begin
        out = 152'he060e26060656660606060eb606060ef60f1f2;
      end
      8'h46: begin
        out = 152'h60e16060646560606060ea606060ee60f0f172;
      end
      8'h47: begin
        out = 152'he06060636460606060e9606060ed60eff07160;
      end
      8'h48: begin
        out = 152'h6060626360606060e8606060ec60eeef706060;
      end
      8'h49: begin
        out = 152'h60616260606060e7606060eb60edee6f6060f2;
      end
      8'h4a: begin
        out = 152'h606160606060e6606060ea60eced6e6060f1f2;
      end
      8'h4b: begin
        out = 152'h6060606060e5606060e960ebec6d6060f0f172;
      end
      8'h4c: begin
        out = 152'h60606060e4606060e860eaeb6c6060eff07172;
      end
      8'h4d: begin
        out = 152'h606060e3606060e760e9ea6b6060eeef707160;
      end
      8'h4e: begin
        out = 152'h6060e2606060e660e8e96a6060edee6f7060f2;
      end
      8'h4f: begin
        out = 152'h60e1606060e560e7e8696060eced6e6f60f172;
      end
      8'h50: begin
        out = 152'he0606060e460e6e7686060ebec6d6e60f07160;
      end
      8'h51: begin
        out = 152'h606060e360e5e6676060eaeb6c6d60ef7060f2;
      end
      8'h52: begin
        out = 152'h6060e260e4e5666060e9ea6b6c60ee6f60f160;
      end
      8'h53: begin
        out = 152'h60e160e3e4656060e8e96a6b60ed6e60f06060;
      end
      8'h54: begin
        out = 152'he060e2e3646060e7e8696a60ec6d60ef606060;
      end
      8'h55: begin
        out = 152'h60e1e2636060e6e7686960eb6c60ee60606072;
      end
      8'h56: begin
        out = 152'he0e1626060e5e6676860ea6b60ed6060607172;
      end
      8'h57: begin
        out = 152'he0616060e4e5666760e96a60ec606060707160;
      end
      8'h58: begin
        out = 152'h606060e3e4656660e86960eb6060606f706060;
      end
      8'h59: begin
        out = 152'h6060e2e3646560e76860ea6060606e6f6060f2;
      end
      8'h5a: begin
        out = 152'h60e1e2636460e66760e96060606d6e6060f172;
      end
      8'h5b: begin
        out = 152'he0e1626360e56660e86060606c6d6060f071f2;
      end
      8'h5c: begin
        out = 152'he0616260e46560e76060606b6c6060ef70f1f2;
      end
      8'h5d: begin
        out = 152'h606160e36460e66060606a6b6060ee6ff0f160;
      end
      8'h5e: begin
        out = 152'h6060e26360e5606060696a6060ed6eeff06072;
      end
      8'h5f: begin
        out = 152'h60e16260e460606068696060ec6deeef607160;
      end
      8'h60: begin
        out = 152'he06160e360606067686060eb6cedee607060f2;
      end
      8'h61: begin
        out = 152'h6060e260606066676060ea6beced606f60f160;
      end
      8'h62: begin
        out = 152'h60e160606065666060e96aebec606e60f06072;
      end
      8'h63: begin
        out = 152'he060606064656060e869eaeb606d60ef6071f2;
      end
      8'h64: begin
        out = 152'h60606063646060e768e9ea606c60ee6070f172;
      end
      8'h65: begin
        out = 152'h606062636060e667e8e9606b60ed606ff07172;
      end
      8'h66: begin
        out = 152'h6061626060e566e7e8606a60ec606eef707172;
      end
      8'h67: begin
        out = 152'h60616060e465e6e7606960eb606dee6f707160;
      end
      8'h68: begin
        out = 152'h606060e364e5e6606860ea606ced6e6f706060;
      end
      8'h69: begin
        out = 152'h6060e263e4e5606760e9606bec6d6e6f6060f2;
      end
      8'h6a: begin
        out = 152'h60e162e3e4606660e8606aeb6c6d6e6060f1f2;
      end
      8'h6b: begin
        out = 152'he061e2e3606560e76069ea6b6c6d6060f0f160;
      end
      8'h6c: begin
        out = 152'h60e1e2606460e66068e96a6b6c6060eff06060;
      end
      8'h6d: begin
        out = 152'he0e1606360e56067e8696a6b6060eeef606060;
      end
      8'h6e: begin
        out = 152'he0606260e46066e768696a6060edee60606060;
      end
      8'h6f: begin
        out = 152'h606160e36065e66768696060eced6060606060;
      end
      8'h70: begin
        out = 152'h6060e26064e56667686060ebec6060606060f2;
      end
      8'h71: begin
        out = 152'h60e16063e46566676060eaeb6060606060f1f2;
      end
      8'h72: begin
        out = 152'he06062e36465666060e9ea6060606060f0f160;
      end
      8'h73: begin
        out = 152'h6061e26364656060e8e96060606060eff060f2;
      end
      8'h74: begin
        out = 152'h60e16263646060e7e86060606060eeef60f1f2;
      end
      8'h75: begin
        out = 152'he06162636060e6e76060606060edee60f0f160;
      end
      8'h76: begin
        out = 152'h6061626060e5e66060606060eced60eff060f2;
      end
      8'h77: begin
        out = 152'h60616060e4e56060606060ebec60eeef60f160;
      end
      8'h78: begin
        out = 152'h606060e3e46060606060eaeb60edee60f06072;
      end
      8'h79: begin
        out = 152'h6060e2e36060606060e9ea60eced60ef6071f2;
      end
      8'h7a: begin
        out = 152'h60e1e26060606060e8e960ebec60ee6070f160;
      end
      8'h7b: begin
        out = 152'he0e16060606060e7e860eaeb60ed606ff06060;
      end
      8'h7c: begin
        out = 152'he06060606060e6e760e9ea60ec606eef6060f2;
      end
      8'h7d: begin
        out = 152'h6060606060e5e660e8e960eb606dee6060f160;
      end
      8'h7e: begin
        out = 152'h60606060e4e560e7e860ea606ced6060f060f2;
      end
      8'h7f: begin
        out = 152'h606060e3e460e6e760e9606bec6060ef60f1f2;
      end
      8'h80: begin
        out = 152'h6060e2e360e5e660e8606aeb6060ee60f0f160;
      end
      8'h81: begin
        out = 152'h60e1e260e4e560e76069ea6060ed60eff06060;
      end
      8'h82: begin
        out = 152'he0e160e3e460e66068e96060ec60eeef606072;
      end
      8'h83: begin
        out = 152'he060e2e360e56067e86060eb60edee606071f2;
      end
      8'h84: begin
        out = 152'h60e1e260e46066e76060ea60eced606070f172;
      end
      8'h85: begin
        out = 152'he0e160e36065e66060e960ebec60606ff071f2;
      end
      8'h86: begin
        out = 152'he060e26064e56060e860eaeb60606eef70f160;
      end
      8'h87: begin
        out = 152'h60e16063e46060e760e9ea60606dee6ff06060;
      end
      8'h88: begin
        out = 152'he06062e36060e660e8e960606ced6eef606060;
      end
      8'h89: begin
        out = 152'h6061e26060e560e7e860606bec6dee60606072;
      end
      8'h8a: begin
        out = 152'h60e16060e460e6e760606aeb6ced6060607160;
      end
      8'h8b: begin
        out = 152'he06060e360e5e6606069ea6bec6060607060f2;
      end
      8'h8c: begin
        out = 152'h6060e260e4e5606068e96aeb6060606f60f160;
      end
      8'h8d: begin
        out = 152'h60e160e3e4606067e869ea6060606e60f06072;
      end
      8'h8e: begin
        out = 152'he060e2e3606066e768e96060606d60ef607160;
      end
      8'h8f: begin
        out = 152'h60e1e2606065e667e86060606c60ee60706072;
      end
      8'h90: begin
        out = 152'he0e1606064e566e76060606b60ed606f607160;
      end
      8'h91: begin
        out = 152'he0606063e465e66060606a60ec606e607060f2;
      end
      8'h92: begin
        out = 152'h606062e364e56060606960eb606d606f60f160;
      end
      8'h93: begin
        out = 152'h6061e263e46060606860ea606c606e60f06060;
      end
      8'h94: begin
        out = 152'h60e162e36060606760e9606b606d60ef606060;
      end
      8'h95: begin
        out = 152'he061e26060606660e8606a606c60ee60606072;
      end
      8'h96: begin
        out = 152'h60e16060606560e76069606b60ed6060607172;
      end
      8'h97: begin
        out = 152'he06060606460e66068606a60ec606060707172;
      end
      8'h98: begin
        out = 152'h6060606360e56067606960eb6060606f707172;
      end
      8'h99: begin
        out = 152'h60606260e46066606860ea6060606e6f707160;
      end
      8'h9a: begin
        out = 152'h606160e36065606760e96060606d6e6f706072;
      end
      8'h9b: begin
        out = 152'h6060e26064606660e86060606c6d6e6f607172;
      end
      8'h9c: begin
        out = 152'h60e16063606560e76060606b6c6d6e60707172;
      end
      8'h9d: begin
        out = 152'he06062606460e66060606a6b6c6d606f707160;
      end
      8'h9e: begin
        out = 152'h6061606360e5606060696a6b6c606e6f7060f2;
      end
      8'h9f: begin
        out = 152'h60606260e460606068696a6b606d6e6f60f160;
      end
      8'ha0: begin
        out = 152'h606160e36060606768696a606c6d6e60f06072;
      end
      8'ha1: begin
        out = 152'h6060e260606066676869606b6c6d60ef607160;
      end
      8'ha2: begin
        out = 152'h60e160606065666768606a6b6c60ee60706072;
      end
      8'ha3: begin
        out = 152'he06060606465666760696a6b60ed606f607160;
      end
      8'ha4: begin
        out = 152'h606060636465666068696a60ec606e60706072;
      end
      8'ha5: begin
        out = 152'h6060626364656067686960eb606d606f6071f2;
      end
      8'ha6: begin
        out = 152'h60616263646066676860ea606c606e6070f160;
      end
      8'ha7: begin
        out = 152'h606162636065666760e9606b606d606ff06060;
      end
      8'ha8: begin
        out = 152'h6061626064656660e8606a606c606eef606060;
      end
      8'ha9: begin
        out = 152'h60616063646560e76069606b606dee606060f2;
      end
      8'haa: begin
        out = 152'h606062636460e66068606a606ced606060f1f2;
      end
      8'hab: begin
        out = 152'h6061626360e560676069606bec606060f0f160;
      end
      8'hac: begin
        out = 152'h60616260e460666068606aeb606060eff060f2;
      end
      8'had: begin
        out = 152'h606160e3606560676069ea606060eeef60f172;
      end
      8'hae: begin
        out = 152'h6060e2606460666068e9606060edee60f071f2;
      end
      8'haf: begin
        out = 152'h60e1606360656067e8606060eced60ef70f1f2;
      end
      8'hb0: begin
        out = 152'he0606260646066e7606060ebec60ee6ff0f172;
      end
      8'hb1: begin
        out = 152'h606160636065e6606060eaeb60ed6eeff071f2;
      end
      8'hb2: begin
        out = 152'h6060626064e5606060e9ea60ec6deeef70f172;
      end
      8'hb3: begin
        out = 152'h60616063e4606060e8e960eb6cedee6ff071f2;
      end
      8'hb4: begin
        out = 152'h606062e3606060e7e860ea6beced6eef70f1f2;
      end
      8'hb5: begin
        out = 152'h6061e2606060e6e760e96aebec6dee6ff0f172;
      end
      8'hb6: begin
        out = 152'h60e1606060e5e660e869eaeb6ced6eeff07160;
      end
      8'hb7: begin
        out = 152'he0606060e4e560e768e9ea6bec6deeef706072;
      end
      8'hb8: begin
        out = 152'h606060e3e460e667e8e96aeb6cedee6f607160;
      end
      8'hb9: begin
        out = 152'h6060e2e360e566e7e869ea6beced6e60706072;
      end
      8'hba: begin
        out = 152'h60e1e260e465e6e768e96aebec6d606f607160;
      end
      8'hbb: begin
        out = 152'he0e160e364e5e667e869eaeb6c606e60706060;
      end
      8'hbc: begin
        out = 152'he060e263e4e566e768e9ea6b606d606f6060f2;
      end
      8'hbd: begin
        out = 152'h60e162e3e465e667e8e96a606c606e6060f172;
      end
      8'hbe: begin
        out = 152'he061e2e364e566e7e869606b606d6060f071f2;
      end
      8'hbf: begin
        out = 152'h60e1e263e465e6e768606a606c6060ef70f160;
      end
      8'hc0: begin
        out = 152'he0e162e364e5e6676069606b6060ee6ff06060;
      end
      8'hc1: begin
        out = 152'he061e263e4e5666068606a6060ed6eef6060f2;
      end
      8'hc2: begin
        out = 152'h60e162e3e465606760696060ec6dee6060f160;
      end
      8'hc3: begin
        out = 152'he061e2e364606660686060eb6ced6060f06060;
      end
      8'hc4: begin
        out = 152'h60e1e263606560676060ea6bec6060ef6060f2;
      end
      8'hc5: begin
        out = 152'he0e162606460666060e96aeb6060ee6060f160;
      end
      8'hc6: begin
        out = 152'he061606360656060e869ea6060ed6060f06072;
      end
      8'hc7: begin
        out = 152'h60606260646060e768e96060ec6060ef6071f2;
      end
      default: begin
        out = 152'h00000000000000000000000000000000000000;
      end
    endcase
  end
endmodule
